package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	httptransport "github.com/go-swagger/go-swagger/httpkit/client"
	"github.com/go-swagger/go-swagger/spec"
	"github.com/go-swagger/go-swagger/strfmt"
)

// The Default auth HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new auth HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Auth {
	swaggerSpec, err := spec.New(SwaggerJSON, "")
	if err != nil {
		// the swagger spec is valid because it was used to generated this code.
		panic(err)
	}
	if formats == nil {
		formats = strfmt.Default
	}
	return New(httptransport.New(swaggerSpec), formats)
}

// New creates a new auth client
func New(transport client.Transport, formats strfmt.Registry) *Auth {
	cli := new(Auth)
	cli.Transport = transport

	return cli
}

// Auth is a client for auth
type Auth struct {
	Transport client.Transport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Auth) SetTransport(transport client.Transport) {
	c.Transport = transport

}
